Change: added git checkout
bikol/DINO202122 pull request #5
Opened 2021-11-05 20:26 UTC by korzepadawid

I've added ``git checkout "branch"`` description.

2021-11-09 09:04 UTC, bikol requested changes
proszę zmergować

2021-11-10 09:20 UTC, bikol requested changes
proszę ponownie zmergować

2021-11-11 14:27 UTC, korzepadawid commented
.

2021-11-14 10:10 UTC, korzepadawid commented
.

2021-11-18 10:32 UTC, bikol requested changes
proszę zmergować

2021-11-19 13:07 UTC, merged